# fly.toml app configuration file generated for docker-alpine-to1wiq on 2026-05-29T13:00:23Z
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'docker-alpine-to1wiq'
primary_region = 'ams'

[build]

[[mounts]]
  source = 'out'
  destination = '/out'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 1
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256
